language: node_js
node_js: stable

env:
  global:
    - ENCRYPTION_LABEL="4a24edc7e7d1"

before_install:
  - cd reference-implementation

script:
  - npm test
  - cd ..
  - make deploy

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always
